name: autofix.ci # must named autofix.ci

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run lint --fix

      - uses: autofix-ci/action@v1.3.1
        with:
          commit-message: 'chore: autofix by ci'
